package com.NoU.Crafts;

/**
 * @author Toonu
 */
public enum CSubclass {
    APC, IFV, AFV, MBT, SAM, SPAAG, LIGHTMULTIROLE, MEDIUMMULTIROLE, HEAVYMULTIROLE, LARGEAIRFRAME, VERYLARGEAIRFRAME,
    CORVETTE, FRIGATE, DESTROYER, CRUISER, BATTLECRUISER, BATTLESHIP, LIGHTCARRIER, CARRIER;
}
